# Generated by Django 5.0.7 on 2024-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book_table1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=55)),
                ("Email", models.EmailField(max_length=55)),
                ("Number", models.IntegerField(max_length=10)),
                ("Date", models.DateTimeField()),
                ("Person", models.IntegerField()),
            ],
        ),
    ]
